# docker-compose.yml
version: '3.9'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: ["3306:3306"]
    volumes: ['./init.sql:/docker-entrypoint-initdb.d/init.sql']

  eureka:
    build: ./discovery
    ports: ["8761:8761"]
    depends_on: [mysql]

  gateway:
    build: ./gateway
    ports: ["8080:8080"]
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    depends_on: [eureka]

  catalog:
    build: ./catalog
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catalog_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    depends_on: [mysql, eureka]

  order:
    build: ./order
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    depends_on: [mysql, eureka]