name: CI/CD para Microservicios

on:
  push:
    branches: [ "main" ] # Se activa solo con push a la rama principal

jobs:
  # --- TRABAJO 1: Construir y Probar ---
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Definimos los servicios (deben coincidir con los nombres de las carpetas/módulos de Maven)
        service: [ catalog, order, gateway, discovery ]
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Ejecutar Pruebas para el servicio ${{ matrix.service }}
        # El comando -pl ejecuta el build solo para el módulo especificado
        run: mvn -B test --file ${{ matrix.service }}/pom.xml

  # --- TRABAJO 2: Construir y Publicar Imágenes Docker ---
  build-and-push-docker-image:
    needs: build-test # Este trabajo solo se ejecuta si 'build-test' fue exitoso
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ catalog, order, gateway, discovery ]
    permissions:
      contents: read
      packages: write # Permiso para escribir en GitHub Packages (GHCR)

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login a GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Este token lo provee GitHub automáticamente

      - name: Construir y Publicar la imagen Docker
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest